alias: 'tuer oeffen licht an'
initial_state: on
trigger:
- platform: state
  entity_id: binary_sensor.mija_door
  to: 'on'
condition:
- condition: state
  entity_id: binary_sensor.motion_vr
  state: 'off'
action:
- service: scene.turn_on
  entity_id: scene.vr_welcome