
alias: motion_vr
initial_state: 'on'
hide_entity: true
trigger:
  - platform: state
    entity_id:
      - binary_sensor.motion_vr
    to: 'on'
condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: sensor.house_mode_special
      state: 'normal'
    - condition: state
      entity_id: sensor.house_mode_special
      state: 'Movie Time'
action:
# - service: scene.turn_on
#   data_template:
#     entity_id: >-
#       {% if is_state("sensor.house_mode_state", "nacht") %}
#         scene.vr_nacht
#       {% elif is_state("sensor.house_mode_state", "abend") %}
#         scene.vr_abend
#       {% elif is_state("sensor.house_mode_state", "tag") %}
#         scene.vr_tag
#       {% elif is_state("sensor.house_mode_state", "morgens") %}
#         scene.vr_tag
#       {% endif %}

- service: light.turn_on
  data_template:
    entity_id: light.hue_ambiance
    brightness: "{{ states('input_number.' + states('sensor.house_mode_state_eng') + '_time_brightness_value') |int }}"
    color_temp:  "{{ states('input_number.' + states('sensor.house_mode_state_eng') + '_time_color_temp_value') |int }}"
    transition: "{{ states('input_number.' + states('sensor.house_mode_state_eng') + '_time_transition_value') |int }}"

- service: light.turn_on
  data_template:
    transition: "{{ states('input_number.' + states('sensor.house_mode_state_eng') + '_time_transition_value') | int }}" # issue
    brightness: "{{ states('input_number.' + states('sensor.house_mode_state_eng') + '_time_brightness_value') | int }}"
    entity_id: light.innr

#- service: light.turn_on
#  data_template:
#    entity_id: light.vorraum_white
#    brightness: "{{ states('input_number.' + states('sensor.house_mode_state_eng') + '_time_brightness_value') |int }}"
##    color_temp:  "{{ states('input_number.' + states('sensor.house_mode_state_eng') + '_time_color_temp_value') |int }}"
#    transition: "{{ states('input_number.' + states('sensor.house_mode_state_eng') + '_time_transition_value') |int }}"

- service: light.turn_on
  data_template:
    entity_id: light.vorraum_white
    brightness: >
                {%- set brightness = states('input_number.' + states('sensor.house_mode_state_eng') + '_time_brightness_value') | int %}
                {{ brightness * 1.3 | int if brightness * 1.3 <= 255 else 255 | int }}
    transition: "{{ states('input_number.' + states('sensor.house_mode_state_eng') + '_time_transition_value') |int }}"



# vorraum_white

# nacht
 # only LS 
 # light.vorraum_lightstrip_mq 

 # abend # 3
 # tag 3 