alias: motion_vr_kommode_aus
initial_state: 'on'
trigger:
  - platform: state
    entity_id: binary_sensor.motion_vr
    to: 'off'
    for:
      minutes: 10
condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: sensor.house_mode_special
      state: 'normal'
    - condition: state
      entity_id: sensor.house_mode_special
      state: 'Gäste'
action:
- service: scene.turn_on
  entity_id: scene.vr_aus