alias: Bath boolean Baden mode I
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.boolean_baden
    to: 'on'
action:
  - service: scene.turn_on
    entity_id: scene.baden
  - service: automation.turn_off
    entity_id: automation.motion_bad_aus
  - service: automation.turn_off
    entity_id: automation.motion_bad_an
  - service: automation.turn_off
    entity_id: automation.motion_badkueche_aus