alias: Bath boolean zaehneputzen mode
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.boolean_zaehneputzen
    to: 'on'
action:
  - service: scene.turn_on
    entity_id: scene.zaehneputzen
  - delay: '00:10:00'
  - service: input_boolean.turn_off
    entity_id: input_boolean.boolean_zaehneputzen