alias: Bath Automate Baden mode O
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.boolean_baden
    to: 'off'
  - platform: state
    entity_id: light.bad_yeelight
    to: 'unavailable'
action:
  - service: automation.turn_on
    entity_id: automation.motion_bad_aus
  - service: automation.turn_on
    entity_id: automation.motion_bad_an
  - service: automation.turn_on
    entity_id: automation.motion_badkueche_aus