alias: Bath boolean schmink mode
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.boolean_schmink_mode
    to: 'on'
action:
  - service: scene.turn_on
    entity_id: scene.schminken
  - delay: '00:20:00'
  - service: input_boolean.turn_off
    entity_id: input_boolean.boolean_schmink_mode