alias: bath_yeelight_unavailable_turn_bath_off
initial_state: 'on'
trigger:
  - platform: state
    entity_id: light.bad_yeelight
    to: 'unavailable'
action:
  - service: script.turn_on
    entity_id: script.bad_and_modes_off