#https://www.home-assistant.io/components/flic/
# The flic platform allows you to receive click events from flic smart buttons.
# The platform does not directly interact with the buttons, but communicates with a flic service that manages the buttons. 
# The service can run on the same instance as Home Assistant or any other reachable machine.


binary_sensor:
  - platform: flic
    discovery: true
    host: !secret flic_ip

    