title: ''
views:
## MINIMAL EXAMPLE START
#  - title: Example
#    cards:
#      - type: markdown
#        title: Lovelace
#        content: >
#          Welcome to your **Lovelace UI**.
## MINIMAL EXAMPLE END




#  - !include lovelace/views/xxx.yaml
  - !include lovelace/001_dashboard.yaml
  - !include lovelace/views/040_floorplan.yaml
  - !include lovelace/views/002_shoppinglist.yaml
  - !include lovelace/views/030_remotes.yaml
  - !include lovelace/views/009_devcard.yaml
  - !include lovelace/050_schlafzimmer.yaml
  - !include lovelace/views/100_bad.yaml
  - !include lovelace/views/777_falcion.yaml
  - !include lovelace/views/070_wohnzimmer.yaml
  - !include lovelace/099_gosund.yaml

decluttering_templates:
  gosund:
    default:  # This is optional
      - number: 0
      - name: DEFAULT
    card:
      entities:
        - entity: switch.gosund_[[number]]_relay
        - entity: binary_sensor.gosund_[[number]]_running
        - entity: sensor.gosund_[[number]]_voltage
        - entity: sensor.gosund_[[number]]_amperage
        - entity: sensor.gosund_[[number]]_wattage
        - entity: sensor.gosund_[[number]]_total_daily_energy
        - entity: switch.gosund_[[number]]_led_blue
        - entity: switch.gosund_[[number]]_led_red
      title: '[[name]]'
      type: entities


  gosund2:
    card:
      entities:
        - entity: switch.[[number]]_relay
        - entity: binary_sensor.[[number]]_running
        - entity: sensor.[[number]]_voltage
        - entity: sensor.[[number]]_amperage
        - entity: sensor.[[number]]_wattage
        - entity: sensor.[[number]]_total_daily_energy
        - entity: switch.[[number]]_led_blue
        - entity: switch.[[number]]_led_red
      title: '[[name]]'
      type: entities

  sonoffpow:
    card:
      entities:
        - entity: switch.[[number]]_relay
        - entity: binary_sensor.[[number]]_running
        - entity: sensor.[[number]]_voltage
        - entity: sensor.[[number]]_amperage
        - entity: sensor.[[number]]_wattage
        - entity: sensor.[[number]]_total_daily_energy
        - entity: switch.[[number]]_led_blue
    #    - entity: switch.[[number]]_led_red
      title: '[[name]]'
      type: entities


  temp_graph:
    card:
      type: custom:mini-graph-card
      entities:
        - 'sensor.[[temp_sensor]]'
      hours_to_show: 6
      update_interval: 60
      line_color: blue
      line_width: 4
      font_size: 50
      points_per_hour: 6
      color_thresholds:
      #https://cdn.discordapp.com/attachments/397426163649216512/603935227676590131/txint_eur2_whf3.png
      #https://discordapp.com/channels/330944238910963714/397426163649216512/603935220848263190
# http://www.meteociel.fr/observations-meteo/temperatures.php
        - value: -10
          color: "#ffffff"
        - value: -5
          color: "009AFF"
        - value: -2
          color: "2FCDFF"
        - value: 0
          color: "66FFFF"
        - value: 5
          color: "#66ff66"
        - value: 8
          color: "#66ff5e"
        - value: 10
          color: "#66ff00"
        - value: 13
          color: "#ffff09"
        - value: 14
          color: "#ffff84"
        - value: 16
          color: "#fde851"
        - value: 19
          color: "#ffcc00"
        - value: 21
          color: "#ff9900"
        - value: 22
          color: "#ff6600"
        - value: 24
          color: "#ff6600"
        - value: 25
          color: "#ff3333"
        - value: 32
          color: "#b20000"
        - value: 36
          color: "#990000"
        - value: 39
          color: "800050"
        - value: 40
          color: "#800050"
        - value: 41
          color: "#a00077"
        - value: 42
          color: "#cc00cc"


cch:
  menu: overflow
  options: clock
  clock_format: 24
  redirect: false
  chevrons: false
  date_locale: de-AT
  swipe: true
  swipe_amount: 40
  swipe_animate: flip

  exceptions:
    - conditions:
        user_agent: Mobile
        media_query: "(max-width: 600px)"
        user: WB
      config:
        options: hide
        notifications: overflow

    - conditions:
        user: falcion
      config:
        #voice: show
        header: false
        kiosk_mode: true
        disable_sidebar: true









resources:




  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
    
#  https://github.com/bramkragten/swipe-card
  - url: /community_plugin/swipe-card/swipe-card.js
#  - url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/swipe-card/swipe-card.js
    type: module


##  # https://github.com/maykar?tab=repositories  
### https://github.com/maykar/lovelace-swipe-navigation
#  - url: /community_plugin/lovelace-swipe-navigation/swipe-navigation.js
#    type: js


# https://github.com/maykar/compact-custom-header
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module


#
## https://github.com/thomasloven?tab=repositories

## https://github.com/thomasloven/lovelace-card-tools
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: js
#
## https://github.com/thomasloven/lovelace-layout-card
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    type: js
#
## https://github.com/thomasloven/lovelace-slider-entity-row
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module
#
## https://github.com/thomasloven/lovelace-fold-entity-row
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: module
#
## https://github.com/thomasloven/lovelace-state-switch
  - url: /customcards/state-switch.js
    type: js
#
## https://github.com/thomasloven/lovelace-toggle-lock-entity-row
  - url: /community_plugin/lovelace-toggle-lock-entity-row/toggle-lock-entity-row.js
    type: js
# https://github.com/thomasloven/lovelace-gap-card
  - url: /community_plugin/lovelace-gap-card/gap-card.js
    type: js
# https://github.com/custom-cards/decluttering-card
  - url: /community_plugin/decluttering-card/decluttering-card.js
    type: module
# #  https://github.com/custom-cards
## https://github.com/custom-cards/tracker-card
##  - type: module
##    url: /customcards/github/custom-cards/tracker-card.js?track=true
## EOL 
## https://github.com/custom-cards/button-card
##  - url: /customcards/github/custom-cards/button-card.js?track=true
##    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
# https://github.com/custom-cards/vertical-stack-in-card
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
## https://github.com/custom-cards/plan-coordinates
##  - url: /customcards/plan-coordinates.js?v=1
#  - url: /community_plugin/plan-coordinates/plan-coordinates.js
#    type: js
#W
### https://github.com/kalkih
### https://github.com/kalkih/mini-graph-card
##  - url: /local/mini-graph-card-bundle.js?track=true
##    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module

### https://github.com/kalkih/mini-media-player
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
#
## ... mybe https://github.com/rdehuyss/homeassistant-lovelace-google-calendar-card
##  - type: js
##    url: /customcards/calendar-card.js

  - url: /community_plugin/calendar-card/calendar-card.js
    type: js
#
#
## More problems then helping
##  - url: /customcards/github/nervetattoo/simple-thermostat.js?track=true
##    type: module
#
## unused
##  - type: js
##    url: /customcards/kiosk.js
#
## depriciated
##  - type: module
##    url: /customcards/useful-markdown-card.js