alias: V UP
hide_entity: true
initial_state: on
trigger:
  platform: mqtt
  topic: 'lights/dimmer_bad'
condition:
  condition: template
  value_template: "{{ 'up-press' == trigger.payload_json.action }}"
action:
- service: scene.turn_on
  entity_id: scene.bad_dimmer_up
 
