
alias: ikeadimmer_left
initial_state: on
trigger:
  - platform: mqtt
    topic: 'lights/ikea_dimmer'
condition:
- condition: or
  conditions:
    - condition: template
      value_template: "{{ 'rotate_left' == trigger.payload_json.action }}"
#- condition: template
#  value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
  # eh.. Error during template condition: UndefinedError: 'dict object' has no attribute 'from_state'

action:
  - service: media_player.media_previous_track
    data_template:
    #  entity_id: "{% for state in states.media_player -%} {% if state.state_with_unit == 'playing' %}{{ state.entity_id| lower }}{% endif %}{% endfor %}" 
      entity_id: |
        {% for state in states.media_player -%}
        {% if state.state_with_unit == 'playing' %}
        {{ (state.entity_id|lower) }}, 
        {% endif %}
        {% endfor %}

  - delay: '00:00:05'

  #note:
  # deleted the ,
  # | lower }}, {% end
