alias: bedroom_pc_cube_on
hide_entity: true
initial_state: 'on'
trigger:
  - platform: mqtt
    topic: 'lights/sz_cube_pc'
condition:
  condition: or
  conditions:
    - condition: template
      value_template: "{{ 'rotate_right' == trigger.payload_json.action }}"
    - condition: template
      value_template: "{{ 'tap' == trigger.payload_json.action }}"
    #    - condition: template
    #      value_template: "{{ (trigger.payload_json.angle)  > 32  }}"
  #      - condition: template
  #        value_template: "{{ states.sensor.cube.state == 'rotate_right' }}"
  #      - condition: template
  #        value_template: "{{ state_attr('sensor.cube', 'angle') > 32 }}"
action:
  #   - service: script.turn_on
  #     entity_id: script.dash_pc_hochfahren
- service: automation.turn_off
  entity_id: automation.automationpc_off
- data:
    entity_id: switch.pc_relay
  service: switch.turn_on
- data:
    brightness: '254'
    color_temp: 330
    entity_id: light.sz_lightstrip_plus
    transition: 10
  service: light.turn_on
- data:
    entity_id: switch.schreibtisch
  service: switch.turn_on
- wait_template: "{{ states.sensor.pc_wattage.state|int > 15 }}"
  timeout: '00:01:00'
  continue_on_timeout: 'true'
- service: automation.turn_on
  entity_id: automation.automationpc_off
