alias: sz_vibration_all
hide_entity: true
initial_state: 'on'
trigger:
- platform: mqtt
  topic: 'lights/vibration_sensor'
condition:
  - condition: template
    value_template: "{{ is_state('group.bedroom', 'off') }}"
  - condition: time
    after: '17:00:00'
    before: '01:30:00'
action:
- service: scene.turn_on
  entity_id: scene.aus_aus
