

binary_sensor:
  - platform: "mqtt"
    name: motion_bad
    state_topic: "lights/motion_bad"
    availability_topic: "lights/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: "motion"

sensor:

  - platform: "mqtt"
    name: motion_bad_battery
    state_topic: "lights/motion_bad"
    availability_topic: "lights/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
