binary_sensor:
  - platform: template
    sensors:
      badkueche:
        friendly_name: "Bad und Küche"
        device_class: motion
        value_template: >-
            {{ is_state('binary_sensor.motion_bad', 'on') or is_state('binary_sensor.motion_kueche', 'on') }}