

sensor:

  - platform: template
    sensors:
      home_temperature:
        friendly_name: "Außentemperatur"
        unit_of_measurement: 'C°'
        value_template: "{{ state_attr('weather.home', 'temperature') }}"
