binary_sensor:

  - platform: "mqtt"
    name: motion_wz
    state_topic: "lights/motion_wz"
    availability_topic: "lights/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: "motion"


sensor:
  - platform: "mqtt"
    name: motion_wz_temp
    state_topic: "lights/motion_wz"
    availability_topic: "lights/bridge/state"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value_json.temperature }}"


  - platform: "mqtt"
    name: motion_wz_lux
    state_topic: "lights/motion_wz"
    availability_topic: "lights/bridge/state"
    unit_of_measurement: "lx"
    device_class: "illuminance"
    value_template: "{{ value_json.illuminance }}"


  - platform: "mqtt"
    name: motion_wz_battery
    state_topic: "lights/motion_wz"
    availability_topic: "lights/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"


  - platform: "mqtt"
    name: motion_wz_linkquality
    state_topic: "lights/motion_wz"
    availability_topic: "lights/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"
