

alias: 'Telegram bot türöffner'
initial_state: on
hide_entity: true
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/tuer'
action:
  - service: script.turn_on
    entity_id: script.tueroeffner
