alias: 'Telegram bot that reply pong to ping'
hide_entity: true
initial_state: on
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/ping'
action:
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.user_id }}'
      message: "Pong, Es ist {{now().strftime('%H:%M:%S %Y-%m-%d')}}  Message von {{ trigger.event.data['user_id'] }} "

#  {{now().strftime("%H:%M")}}