
alias: bath_Flic_w_hold
trigger:
  platform: event
  event_type: flic_click
  event_data:
    button_name: flic_80e4da736508
    click_type: hold
action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.gmusic_player_speakers
      option: bad
  - service: input_select.select_option
    data_template:
      entity_id: input_select.gmusic_player_playlist
      option: "{% for item in state_attr('input_select.gmusic_player_playlist', 'options') | random  %}{{ item }}{% endfor %}"
  - service: media_player.media_play
    entity_id: media_player.gmusic_player


