alias: bath_Flic_w_Single
trigger:
  platform: event
  event_type: flic_click
  event_data:
    button_name: flic_80e4da736508
    click_type: double
action:
  - service: media_player.media_previous_track
    entity_id: media_player.gmusic_player


