alias: Notify when new device discovered
trigger:
  platform: event
  event_type: device_tracker_new_device
action:
  - service: persistent_notification.create
    data_template:
      message: >
        New device:
        {{trigger.event.data.host_name}}
        ({{trigger.event.data.entity_id}})
      title: New device
