alias: HA Start - day
initial_state: 'on'
hide_entity: true
trigger:
  - platform: homeassistant
    event: start
condition:
  - condition: time
    after: '06:00:00'
    before: '18:00:00'
action:
    service: input_boolean.turn_on
    entity_id: input_boolean.boolean_day_time