
alias: sz_pc_off
initial_state: on
trigger:
- above: '0'
  below: '12'
  entity_id: sensor.pc_wattage
  platform: numeric_state
condition: []
action:
- delay: "00:00:30"
- wait_template: "{{ states('sensor.pc_wattage')|int < 12 }}"
  timeout: '00:00:02'
  continue_on_timeout: 'false'
- data:
    entity_id: switch.pc_relay
  service: switch.turn_off
- data:
    entity_id: switch.schreibtisch
  service: light.turn_off
- data:
    entity_id: light.schreibtisch_bulb
  service: light.turn_off
#  - alias: AutomationAutomationPC_onoff
#    initial_state: 'on'
#    hide_entity: true
#    trigger:
#      - platform: state
#        entity_id: switch.pc_relay
#        to: 'on'
#    action:
#    - service: automation.turn_off
#      entity_id: automation.automationpc_off
#    - delay: '00:01:30'
#    - service: automation.turn_on
#      entity_id: automation.automationpc_off
