alias: bath_ikea_prev
initial_state: 'on'
trigger:
- platform: mqtt
  topic: 'lights/ikea_musik'
condition:
  condition: or
  conditions:
    - condition: template
      value_template: "{{ 'arrow_left_click' == trigger.payload_json.action }}"
#    - condition: template
#      value_template: "{{ 'brightness_down_hold' == trigger.payload_json.action }}"
#    - condition: template
#      value_template: "{{ 'brightness_down_releas' == trigger.payload_json.action }}"

# arrow_left_click, arrow_right_click, arrow_right_hold, toggle

#       {% set map = {
#              "brightness_down_click": "state_attr('media_player.bad', 'volume_level')|round(2)|float - 0.1 | float",
#              "brightness_up_click": "state_attr('media_player.bad', 'volume_level')|round(2)|float + 0.1 | float",
#              "default": "unused"
#          }%}
#          {{ map[trigger.payload_json.action] if trigger.payload_json.action in map else map["default"] }}
action:
- service: media_player.media_previous_track
  data_template:
    entity_id: media_player.gmusic_player



