alias: kitchen entrance light 1
initial_state: on
trigger:
  platform: mqtt
  topic: 'lights/xiaomibutton_k'
condition:
- condition: template
  value_template: "{{ 'single' == trigger.payload_json.click }}"
action:
- service: scene.turn_on
  data_template:
    entity_id: >-
      {% if is_state("light.kuchenlicht", "off") %}
      scene.kochen
      {% else %}
      scene.kueche_aus
      {% endif %}
- service_template: >-
    {% if is_state("light.kuchenlicht", "off") %}
    input_boolean.turn_on
    {% else %}
    input_boolean.turn_off
    {% endif %}
  entity_id: input_boolean.kitchen_movement



