alias: house_state_Automate Movie time
initial_state: 'on'
trigger:
  - platform: state
    entity_id: switch.tv_relay
    to: 'on'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.boolean_movie_mode



#      - platform: state
#        entity_id: sensor.remote_entertainment
#        to: 'Netflix'