alias: Automate Movie time off
initial_state: 'on'
trigger:
  - platform: state
    entity_id: switch.tv_relay
    to: 'off'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.boolean_movie_mode
