---
alias: livingroom_tv_IR_
initial_state: 'on'
hide_entity: true
trigger:
- platform: state
  entity_id:
    - binary_sensor.tv_running
- platform: state
  entity_id:
    - sensor.ir
action:
#- service: switch.turn_on
#  entity_id: switch.tv_relay, switch.gosund_11_relay
- service_template: >
    {% if is_state("binary_sensor.tv_running", "on") -%}
      switch.turn_on
    {%- else -%}
      switch.turn_off
    {%- endif %}
  data:
    entity_id: switch.gosund_11_relay




# alias: 'Share state test'
# trigger:
#   - platform: state
#     entity_id: 
#       - switch.tv_relay
#       - switch.gosund_11_relay
# action:
#   - service_template: "homeassistant.turn_{{ trigger.to_state.state | lower}}"
#     data_template:
#       entity_id: >-
#         {% set entities = ["light", "switch"] %}
#         {{ entities |reject("equalto", trigger.entity_id)|list }}

#         # Invalid config for [automation]: 
#         # Entity ID switch.tv_relay, 
#         # is an invalid entity id for dictionary value @ data['trigger'][0]['entity_id']. Got None. (See ?, line ?). 
#         # {% set entities = ["light", "switch"] %}