alias: livingroom_tv_off
initial_state: on
trigger:
- platform: state
  entity_id: binary_sensor.tv_running
  from: 'on'
  to: 'off'
  for: '00:00:06'
# - below: '15'
#   entity_id: sensor.tv_wattage
#   platform: numeric_state
#   for:
#     seconds: 20
condition: []
action:
- service: switch.turn_off
  data:
    entity_id: switch.tv_relay, switch.gosund_11_relay

#- service: switch.turn_off
#  entity_id: switch.gosund_11_relay

