alias: livingroom_tv_IR_Blau
initial_state: 'on'
hide_entity: true
trigger:
  - platform: state
    entity_id:
      - sensor.ir
    to: 'E0E06897' #blau
action:
- service: scene.turn_on
  entity_id: scene.wz_aus